# Default parameters for running ANTARES

audiometry_dir:
  "/Volumes/G_USZ_ORL$/Research/ANTINOMICS/data/audiometry" # path to a folder of audiometry data -> .mat files (must have left and right in it)

subjects_dir:
  "/Users/payamsadeghishabestari/temp_folder/antares_test" # path to a folder where subject information will be stored

videos_dir:
  "/Users/payamsadeghishabestari/ANT/imgs" # path to a folder where videos are stored

models_dir:
  "/Volumes/Extreme_SSD/payam_data/Tinnorm/models/preproc_2" # path to a folder where norm models are stored

baseline_duration:
  120 # duration of baseline RS eeg recording (in seconds).
main_duration:
  20 # duration of main RS eeg recording (in seconds). 
